In [29]:
import pandas as pd
import numpy as np

From 4 csv files i remove some empty and useless columns and than import to this notebook.

In [30]:
jeff=pd.read_excel("jefferson parish cash buyers.xlsx")

In [31]:
neworl=pd.read_excel("new orleans cash transactions.xlsx")

In [32]:
slidell=pd.read_excel("slidell cash buyer list.xlsx")

In [33]:
baton=pd.read_excel("baton rouge and surround areas cash sales.xlsx")

In [34]:
jeff.shape

(481, 23)

In [35]:
neworl.shape

(469, 14)

In [36]:
slidell.shape

(137, 15)

In [37]:
baton.shape

(941, 18)

In [38]:
jeff["PROPERTY ADDRESS"]=range(481)

In [39]:
jeff.tail()

PROPERTY ADDRESS PROPERTY STREET NAME SUFFIX PROPERTY CITY     COUNTY  \
476               476                          Dr      Metairie  Jefferson   
477               477                          Dr      Westwego  Jefferson   
478               478                         Ave      Westwego  Jefferson   
479               479                         Ave     Jefferson  Jefferson   
480               480                          Dr       Marrero  Jefferson   

    LAST MARKET SALE DATE  EQUITY ($)  IMPROVED %  IMPROVED VALUE  LAND VALUE  \
476            2019-04-18      241100          88            8980        1180   
477            2019-04-15       91300          78            6190        1790   
478            2019-04-23      119900          68            3800        1800   
479            2019-10-07      117100          53            4200        3740   
480            2019-05-17      128100          60            6150        4120   

    LAST MARKET RECORDING DATE  ... LOT ACREAGE  PRIOR MARKET RECORDING DATE  \
476                 2019-04-22  ...        0.00                   2019-04-22   
477                 2019-04-16  ...        0.00                   2004-10-01   
478                 2019-04-23  ...        0.14                   1976-09-01   
479                 2019-10-08  ...        0.13                   1994-09-01   
480                 2019-05-17  ...        0.11                   1997-07-01   

     PRIOR MARKET SALE DATE  PRIOR MARKET SALE PRICE PROPERTY TAX AMOUNT  \
476              2019-04-18                 235000.0             1262.85   
477                     NaT                      0.0              781.06   
478                     NaT                  21900.0              680.08   
479                     NaT                      0.0              900.40   
480                     NaT                  60500.0             1251.74   

    PROPERTY TYPE  TAX RATE AREA  TAX REDUCTION TOTAL ASSESSED VALUE  \
476           Sfr              1              4                10160   
477           Sfr              4              9                 7980   
478           Sfr              9              5                 5600   
479           Sfr              4              7                 7940   
480           Sfr              7              8                10270   

    LENGTH OF RESIDENCE  
476                   7  
477                   8  
478                   7  
479                   2  
480                   7  

[5 rows x 23 columns]

In [40]:
neworl["PROPERTY ADDRESS"]=range(481,481+469)

In [41]:
neworl.head()

PROPERTY ADDRESS PROPERTY STREET NAME SUFFIX PROPERTY CITY   COUNTY  \
0               481                          St   New Orleans  Orleans   
1               482                          St   New Orleans  Orleans   
2               483                        Blvd   New Orleans  Orleans   
3               484                          St   New Orleans  Orleans   
4               485                          St   New Orleans  Orleans   

  PROPERTY TYPE LAST MARKET SALE DATE  EQUITY ($) LAST MARKET RECORDING DATE  \
0           Sfr            2019-03-28      221448                 2019-04-01   
1           Sfr            2018-12-12      284259                 2018-12-18   
2           Sfr            2019-02-01      136733                 2019-02-05   
3           Sfr            2018-08-21       91930                 2018-09-20   
4           Sfr            2018-04-20       75236                 2018-04-30   

  LAST MARKET SALE DEED TYPE  LAST MARKET SALE PRICE PRIOR MARKET SALE DATE  \
0                 Deed (Reg)                  100000             2019-03-28   
1                 Deed (Reg)                  319000                    NaT   
2                 Deed (Reg)                  105000             1999-02-22   
3                 Deed (Reg)                   50000             2012-12-18   
4                 Deed (Reg)                   57000             1999-03-22   

   PRIOR MARKET SALE PRICE  PROPERTY TAX AMOUNT  LENGTH OF RESIDENCE  
0                  75000.0              1477.63                    2  
1                      NaN              5833.48                    6  
2                  34994.0              1032.22                    4  
3                 104861.0               243.45                   10  
4                  50000.0               972.48                   14

In [42]:
slidell["PROPERTY ADDRESS"]=range(950,950+137)

In [43]:
slidell.tail()

PROPERTY ADDRESS PROPERTY STREET NAME SUFFIX PROPERTY CITY      COUNTY  \
132              1082                        Blvd       Slidell  St Tammany   
133              1083                          Dr       Slidell  St Tammany   
134              1084                          Ct       Slidell  St Tammany   
135              1085                          Ln       Slidell  St Tammany   
136              1086                          Dr       Slidell  St Tammany   

    LAST MARKET RECORDING DATE PROPERTY TYPE  EQUITY ($)  \
132                 2019-10-02           Sfr      709600   
133                 2019-08-28           Sfr      331200   
134                 2019-07-16           Sfr      122700   
135                 2019-01-23           Sfr      155300   
136                 2019-05-01           Sfr      149700   

    LAST MARKET SALE DATE LAST MARKET SALE DEED TYPE  LAST MARKET SALE PRICE  \
132            2019-09-24                 Deed (Reg)                  650000   
133            2019-08-28                 Deed (Reg)                  340000   
134            2019-07-12                 Deed (Reg)                  125000   
135            2019-01-22                 Deed (Reg)                  139271   
136            2018-05-24            Quit Claim Deed                   11543   

    PRIOR MARKET RECORDING DATE PRIOR MARKET SALE DATE  \
132                  2017-11-17             2017-11-15   
133                         NaT                    NaT   
134                         NaT                    NaT   
135                  2005-12-30             2005-12-22   
136                         NaT                    NaT   

     PRIOR MARKET SALE PRICE  PROPERTY TAX AMOUNT  LENGTH OF RESIDENCE  
132                 202000.0              7413.44                    3  
133                      NaN              6136.81                    4  
134                      NaN              1620.59                    5  
135                 193501.0              2473.57                   11  
136                      NaN              1022.09                   19

In [44]:
baton["PROPERTY ADDRESS"]=range(1087,1087+941)

In [45]:
baton.head()

PROPERTY ADDRESS PROPERTY STREET NAME SUFFIX      PROPERTY CITY  \
0              1087                         Ave        Baton Rouge   
1              1088                          Dr  Greenwell Springs   
2              1089                          Rd        Baton Rouge   
3              1090                          Rd        Baton Rouge   
4              1091                          Dr        Baton Rouge   

             COUNTY LAST MARKET RECORDING DATE PROPERTY TYPE  \
0  East Baton Rouge                 2019-03-18   Condominium   
1  East Baton Rouge                 2019-04-01           Sfr   
2  East Baton Rouge                 2019-10-04   Condominium   
3  East Baton Rouge                 2019-03-28           Sfr   
4  East Baton Rouge                 2019-04-08   Condominium   

  PRIOR MARKET RECORDING DATE PRIOR MARKET SALE DATE  PRIOR MARKET SALE PRICE  \
0                  2012-11-14             2012-01-01                  88646.0   
1                  1994-04-25                    NaT                      0.0   
2                  2005-12-20             2005-12-09                 129000.0   
3                         NaT                    NaT                      NaN   
4                  2017-05-08             2017-04-28                 148000.0   

   PROPERTY TAX AMOUNT  LAND VALUE LAST MARKET SALE DATE  \
0              1262.11         500            2019-03-14   
1              1555.94        1400            2019-03-21   
2              1255.94        1000            2019-10-01   
3               659.62        1500            2019-03-26   
4              1768.37        1000            2019-03-01   

  LAST MARKET SALE DEED TYPE  LAST MARKET SALE PRICE  LOT AREA  LOT ACREAGE  \
0                 Deed (Reg)                   55000         0         0.00   
1                 Deed (Reg)                   90000      7965         0.18   
2                 Deed (Reg)                  110000         0         0.00   
3                 Deed (Reg)                  225000     46906         1.08   
4                 Deed (Reg)                  140000         0         0.00   

   BLDG/LIVING AREA  LENGTH OF RESIDENCE  
0             675.0                    9  
1            1360.0                    9  
2             998.0                    2  
3            2038.0                    9  
4               0.0                    9

Let's get same columns in 4 dataframes.

In [46]:
jeffcol=set(jeff.columns)

In [47]:
neworlcol=set(neworl.columns)

In [48]:
slidellcol=set(slidell.columns)

In [49]:
batoncol=set(baton.columns)

In [50]:
samecol=batoncol.intersection(slidellcol, neworlcol, jeffcol)

And now we get unique columns on each dataframes.

In [51]:
batoncol-samecol

{'BLDG/LIVING AREA',
 'LAND VALUE',
 'LOT ACREAGE',
 'LOT AREA',
 'PRIOR MARKET RECORDING DATE'}

In [52]:
slidellcol-samecol

{'EQUITY ($)', 'PRIOR MARKET RECORDING DATE'}

In [53]:
neworlcol-samecol

{'EQUITY ($)'}

In [54]:
jeffcol-samecol

{'EQUITY ($)',
 'IMPROVED %',
 'IMPROVED VALUE',
 'LAND VALUE',
 'LOT ACREAGE',
 'LOT AREA',
 'PRIOR MARKET RECORDING DATE',
 'TAX RATE AREA',
 'TAX REDUCTION',
 'TOTAL ASSESSED VALUE'}

We see, that we don't have "EQUITY" in "baton" dataframe and don't have "PRIOR MARKET RECORDING DATE" in "neworl"

In [55]:
(baton['PRIOR MARKET RECORDING DATE']-baton['PRIOR MARKET SALE DATE']).mean()

Timedelta('6 days 18:58:12.215568')

In [56]:
baton['PRIOR MARKET RECORDING DATE'].isnull().sum()

259

In [57]:
baton['PRIOR MARKET SALE DATE'].isnull().sum()

423

We sow that MARKET RECORDING DATE and SALE DATE don't differ so match and RECORGING DATE more complete than SALE DATE let's change "PRIOR MARKET SALE DATE" column name in neworl dataframe to 'PRIOR MARKET RECORDING DATE' to make our dataframes more similar.

In [58]:
neworl=neworl.rename(columns={"PRIOR MARKET SALE DATE":'PRIOR MARKET RECORDING DATE'})

In our dataframes most columns have jeff dataframe. One of the methods, that I want to calculate probabilities is logistic regression that's why delete columns that doesn't contain in "jeff". We will understand this step later.

In [59]:
set(neworl.columns).intersection(set(baton.columns),set(jeff.columns),set(slidell.columns))

{'COUNTY',
 'LAST MARKET RECORDING DATE',
 'LAST MARKET SALE DATE',
 'LAST MARKET SALE DEED TYPE',
 'LAST MARKET SALE PRICE',
 'LENGTH OF RESIDENCE',
 'PRIOR MARKET RECORDING DATE',
 'PRIOR MARKET SALE PRICE',
 'PROPERTY ADDRESS',
 'PROPERTY CITY',
 'PROPERTY STREET NAME SUFFIX',
 'PROPERTY TAX AMOUNT',
 'PROPERTY TYPE'}

In [60]:
batoncol-jeffcol

{'BLDG/LIVING AREA'}

In [61]:
del baton['BLDG/LIVING AREA']

In [62]:
set(baton.columns)-jeffcol

set()

In [63]:
slidellcol-jeffcol

set()

In [64]:
neworlcol-jeffcol

set()

Let's delete some useless columns

In [65]:
del neworl['LAST MARKET SALE DATE'],baton['LAST MARKET SALE DATE'],jeff['LAST MARKET SALE DATE'],slidell['LAST MARKET SALE DATE']

In [66]:
del baton['PRIOR MARKET SALE DATE'],jeff['PRIOR MARKET SALE DATE'],slidell['PRIOR MARKET SALE DATE']

In [67]:
del neworl['COUNTY'],baton['COUNTY'],jeff['COUNTY'],slidell['COUNTY']

In [68]:
del neworl['PROPERTY CITY'],baton['PROPERTY CITY'],jeff['PROPERTY CITY'],slidell['PROPERTY CITY']

In [69]:
del neworl['PROPERTY TYPE'],baton['PROPERTY TYPE'],jeff['PROPERTY TYPE'],slidell['PROPERTY TYPE']

In [70]:
set(neworl).intersection(set(baton),set(jeff),set(slidell))

{'LAST MARKET RECORDING DATE',
 'LAST MARKET SALE DEED TYPE',
 'LAST MARKET SALE PRICE',
 'LENGTH OF RESIDENCE',
 'PRIOR MARKET RECORDING DATE',
 'PRIOR MARKET SALE PRICE',
 'PROPERTY ADDRESS',
 'PROPERTY STREET NAME SUFFIX',
 'PROPERTY TAX AMOUNT'}

Now let's meke dummy variables from 'PROPERTY STREET NAME SUFFIX' and 'LAST MARKET SALE DEED TYPE' columns.

In [71]:
set(jeff['PROPERTY STREET NAME SUFFIX'].isnull())

{False, True}

I will fill NA values with "rrrr" to put it in variable "other"

In [72]:
jeff['PROPERTY STREET NAME SUFFIX'].fillna("rrrr",inplace=True)

In [73]:
j=pd.get_dummies(jeff['PROPERTY STREET NAME SUFFIX'])

In [74]:
j

Ave  Blvd  Cir  Ct  Dr  Hwy  Ln  Park  Pkwy  Pl  Rd  St  Trce  rrrr
0      0     0    0   0   0    0   0     0     0   0   0   1     0     0
1      0     0    0   0   0    0   0     0     0   0   0   1     0     0
2      1     0    0   0   0    0   0     0     0   0   0   0     0     0
3      0     0    0   0   1    0   0     0     0   0   0   0     0     0
4      1     0    0   0   0    0   0     0     0   0   0   0     0     0
..   ...   ...  ...  ..  ..  ...  ..   ...   ...  ..  ..  ..   ...   ...
476    0     0    0   0   1    0   0     0     0   0   0   0     0     0
477    0     0    0   0   1    0   0     0     0   0   0   0     0     0
478    1     0    0   0   0    0   0     0     0   0   0   0     0     0
479    1     0    0   0   0    0   0     0     0   0   0   0     0     0
480    0     0    0   0   1    0   0     0     0   0   0   0     0     0

[481 rows x 14 columns]

In [75]:
neworl['PROPERTY STREET NAME SUFFIX'].fillna("rrrr",inplace=True)

In [76]:
n=pd.get_dummies(neworl['PROPERTY STREET NAME SUFFIX'])

In [77]:
slidell['PROPERTY STREET NAME SUFFIX'].fillna("rrrr",inplace=True)

In [78]:
s=pd.get_dummies(slidell['PROPERTY STREET NAME SUFFIX'])

In [79]:
baton['PROPERTY STREET NAME SUFFIX'].fillna("rrrr",inplace=True)

In [80]:
b=pd.get_dummies(baton['PROPERTY STREET NAME SUFFIX'])

To make dataframes similar I do folowing steps.

In [81]:
oth=set(j).intersection(set(b),set(n),set(s))

In [82]:
oth

{'Ave', 'Blvd', 'Cir', 'Ct', 'Dr', 'Ln', 'Pl', 'Rd', 'St', 'rrrr'}

In [83]:
set(b.columns)-set(oth)

{'Crk', 'Ext', 'Hwy', 'Pkwy', 'Walk', 'Way'}

In [84]:
b["Other"]=b["Crk"]+b["Ext"]+b["Walk"]+b["Way"]+b["Pkwy"]+b["Hwy"]+b['rrrr']

In [85]:
del b["Crk"],b["Ext"],b["Walk"],b["Way"],b["Pkwy"],b["Hwy"],b['rrrr']

In [86]:
b

Ave  Blvd  Cir  Ct  Dr  Ln  Pl  Rd  St  Other
0      1     0    0   0   0   0   0   0   0      0
1      0     0    0   0   1   0   0   0   0      0
2      0     0    0   0   0   0   0   1   0      0
3      0     0    0   0   0   0   0   1   0      0
4      0     0    0   0   1   0   0   0   0      0
..   ...   ...  ...  ..  ..  ..  ..  ..  ..    ...
936    0     0    0   0   1   0   0   0   0      0
937    0     0    0   0   0   0   0   1   0      0
938    1     0    0   0   0   0   0   0   0      0
939    0     1    0   0   0   0   0   0   0      0
940    1     0    0   0   0   0   0   0   0      0

[941 rows x 10 columns]

In [87]:
set(j.columns)-set(oth)

{'Hwy', 'Park', 'Pkwy', 'Trce'}

In [88]:
j["Other"]=j["Trce"]+j["Park"]+j["Pkwy"]+j["Hwy"]+j['rrrr']

In [89]:
del j["Trce"],j["Park"],j["Pkwy"],j["Hwy"],j['rrrr']

In [90]:
set(s.columns)-set(oth)

{'Cv', 'Loop', 'Row', 'Sq', 'Trl'}

In [91]:
s["Other"]=s["Cv"]+s["Loop"]+s["Row"]+s["Sq"]+s["Trl"]+s['rrrr']

In [92]:
del s["Cv"],s["Loop"],s["Row"],s["Sq"],s["Trl"],s['rrrr']

In [93]:
set(n.columns)-set(oth)

{'Hwy', 'Ter', 'Trce'}

In [94]:
n["Other"]=n["Ter"]+n["Hwy"]+n["Trce"]+n['rrrr']

In [95]:
del n["Ter"],n["Hwy"],n["Trce"],n['rrrr']

In [96]:
print(set(jeff['LAST MARKET SALE DEED TYPE'].isnull()))
print(set(neworl['LAST MARKET SALE DEED TYPE'].isnull()))
print(set(baton['LAST MARKET SALE DEED TYPE'].isnull()))
print(set(slidell['LAST MARKET SALE DEED TYPE'].isnull()))

{False}
{False}
{False}
{False}


In [97]:
j1=pd.get_dummies(jeff['LAST MARKET SALE DEED TYPE'])


In [98]:
n1=pd.get_dummies(neworl['LAST MARKET SALE DEED TYPE'])

In [99]:
b1=pd.get_dummies(baton['LAST MARKET SALE DEED TYPE'])


In [100]:
s1=pd.get_dummies(slidell['LAST MARKET SALE DEED TYPE'])


In [101]:
ot=set(j1).intersection(set(b1),set(n1),set(s1))


In [102]:
set(b1.columns)-set(ot)

{'Contract Of Sale', 'Deed Of Assumption', 'Gift Deed', 'Warranty Deed'}

In [103]:
b1["OTHER1"]=b1['Contract Of Sale']+b1['Deed Of Assumption']+b1['Gift Deed']+b1['Warranty Deed']

In [104]:
del b1['Contract Of Sale'],b1['Deed Of Assumption'],b1['Gift Deed'],b1['Warranty Deed']

In [105]:
set(s1.columns)-set(ot)

{'Contract Of Sale', "Sheriff's Deed"}

In [106]:

s1["OTHER1"]=s1['Contract Of Sale']+s1["Sheriff's Deed"]

In [107]:
del s1['Contract Of Sale'],s1["Sheriff's Deed"]

In [108]:
set(n1.columns)-set(ot)

{'Foreclosure Deed', 'Gift Deed', "Sheriff's Deed", 'Warranty Deed'}

In [109]:
n1["OTHER1"]=n1["Sheriff's Deed"]+n1['Foreclosure Deed']+n1['Gift Deed']+n1['Warranty Deed']

In [110]:
del n1["Sheriff's Deed"],n1['Foreclosure Deed'],n1['Gift Deed'],n1['Warranty Deed']

In [111]:
set(j1.columns)-set(ot)

{'Deed Of Assumption'}

In [112]:
j1["OTHER1"]=j1['Deed Of Assumption']

In [113]:
del j1['Deed Of Assumption']

In [114]:
del jeff['PROPERTY STREET NAME SUFFIX'],neworl['PROPERTY STREET NAME SUFFIX'],slidell['PROPERTY STREET NAME SUFFIX'],baton['PROPERTY STREET NAME SUFFIX']

In [115]:
del jeff['LAST MARKET SALE DEED TYPE'],neworl['LAST MARKET SALE DEED TYPE'],slidell['LAST MARKET SALE DEED TYPE'],baton['LAST MARKET SALE DEED TYPE']

In [116]:
del jeff['TAX RATE AREA']

For evary equity let's calculate how many mounths prior resident owned it. And let's fill NA values with median.

In [117]:
jeff["PRIOR LENGTH OF RESIDENCE"]=(jeff["LAST MARKET RECORDING DATE"]-jeff["PRIOR MARKET RECORDING DATE"])/np.timedelta64(1, 'M')

In [118]:
set(jeff["PRIOR LENGTH OF RESIDENCE"].isnull())

{False, True}

In [119]:
jeff["PRIOR LENGTH OF RESIDENCE"].fillna(jeff["PRIOR LENGTH OF RESIDENCE"].median(),inplace=True)

In [120]:
jeff["PRIOR LENGTH OF RESIDENCE"]=jeff["PRIOR LENGTH OF RESIDENCE"].astype(int)

In [121]:
set(jeff["PRIOR LENGTH OF RESIDENCE"].isnull())

{False}

In [122]:
del jeff["LAST MARKET RECORDING DATE"],jeff["PRIOR MARKET RECORDING DATE"]

And all NAs let's fill with mean.

In [123]:
jeff.fillna(jeff.mean(),inplace=True)


In [124]:
jeff.isnull().sum()

PROPERTY ADDRESS             0
EQUITY ($)                   0
IMPROVED %                   0
IMPROVED VALUE               0
LAND VALUE                   0
LAST MARKET SALE PRICE       0
LOT AREA                     0
LOT ACREAGE                  0
PRIOR MARKET SALE PRICE      0
PROPERTY TAX AMOUNT          0
TAX REDUCTION                0
TOTAL ASSESSED VALUE         0
LENGTH OF RESIDENCE          0
PRIOR LENGTH OF RESIDENCE    0
dtype: int64

In [125]:
baton["PRIOR LENGTH OF RESIDENCE"]=(baton["LAST MARKET RECORDING DATE"]-baton["PRIOR MARKET RECORDING DATE"])/np.timedelta64(1, 'M')

In [126]:
set(baton["PRIOR LENGTH OF RESIDENCE"].isnull())

{False, True}

In [127]:
baton["PRIOR LENGTH OF RESIDENCE"].fillna(baton["PRIOR LENGTH OF RESIDENCE"].median(),inplace=True)

In [128]:
baton["PRIOR LENGTH OF RESIDENCE"]=baton["PRIOR LENGTH OF RESIDENCE"].astype(int)

In [129]:
del baton["LAST MARKET RECORDING DATE"],baton["PRIOR MARKET RECORDING DATE"]

In [130]:
baton.fillna(baton.mean(),inplace=True)

In [131]:
baton.isnull().sum()

PROPERTY ADDRESS             0
PRIOR MARKET SALE PRICE      0
PROPERTY TAX AMOUNT          0
LAND VALUE                   0
LAST MARKET SALE PRICE       0
LOT AREA                     0
LOT ACREAGE                  0
LENGTH OF RESIDENCE          0
PRIOR LENGTH OF RESIDENCE    0
dtype: int64

In [132]:
slidell["PRIOR LENGTH OF RESIDENCE"]=(slidell["LAST MARKET RECORDING DATE"]-slidell["PRIOR MARKET RECORDING DATE"])/np.timedelta64(1, 'M')

In [133]:
set(slidell["PRIOR LENGTH OF RESIDENCE"].isnull())

{False, True}

In [134]:
slidell["PRIOR LENGTH OF RESIDENCE"].fillna(slidell["PRIOR LENGTH OF RESIDENCE"].median(),inplace=True)

In [135]:
slidell["PRIOR LENGTH OF RESIDENCE"]=slidell["PRIOR LENGTH OF RESIDENCE"].astype(int)

In [136]:
del slidell["LAST MARKET RECORDING DATE"],slidell["PRIOR MARKET RECORDING DATE"]

In [137]:
slidell.fillna(baton.mean(),inplace=True)

In [138]:
slidell.isnull().sum()

PROPERTY ADDRESS             0
EQUITY ($)                   0
LAST MARKET SALE PRICE       0
PRIOR MARKET SALE PRICE      0
PROPERTY TAX AMOUNT          0
LENGTH OF RESIDENCE          0
PRIOR LENGTH OF RESIDENCE    0
dtype: int64

In [139]:
neworl["PRIOR LENGTH OF RESIDENCE"]=(neworl["LAST MARKET RECORDING DATE"]-neworl["PRIOR MARKET RECORDING DATE"])/np.timedelta64(1, 'M')

In [140]:
set(neworl["PRIOR LENGTH OF RESIDENCE"].isnull())

{False, True}

In [141]:
neworl["PRIOR LENGTH OF RESIDENCE"].fillna(neworl["PRIOR LENGTH OF RESIDENCE"].median(),inplace=True)

In [142]:
neworl["PRIOR LENGTH OF RESIDENCE"]=neworl["PRIOR LENGTH OF RESIDENCE"].astype(int)

In [143]:
del neworl["LAST MARKET RECORDING DATE"],neworl["PRIOR MARKET RECORDING DATE"]

In [144]:
neworl.fillna(baton.mean(),inplace=True)

In [145]:
neworl.isnull().sum()

PROPERTY ADDRESS             0
EQUITY ($)                   0
LAST MARKET SALE PRICE       0
PRIOR MARKET SALE PRICE      0
PROPERTY TAX AMOUNT          0
LENGTH OF RESIDENCE          0
PRIOR LENGTH OF RESIDENCE    0
dtype: int64

Now I arrange columns by same oreder in three dataframes and attach unique values.

In [146]:
t=set(jeff.columns).intersection(set(neworl.columns), set(baton.columns), set(slidell.columns))
h=list(t)

In [147]:
set(neworl.columns)-t

{'EQUITY ($)'}

In [148]:
set(baton.columns)-t

{'LAND VALUE', 'LOT ACREAGE', 'LOT AREA'}

In [149]:
set(slidell.columns)-t

{'EQUITY ($)'}

In [150]:
jeff=jeff[h+list(set(jeff.columns)-t)]

In [151]:
baton=baton[h+list(set(set(baton.columns)-t))]

In [152]:
neworl=neworl[h+list(set(neworl.columns)-t)]

In [153]:
slidell=slidell[h+list(set(slidell.columns)-t)]

Thare are 0 values in dataframes insted of NA, I also fill them with mean.

In [154]:
neworl['LENGTH OF RESIDENCE'].replace(to_replace=0, value=neworl['LENGTH OF RESIDENCE'].mean(),inplace=True)
neworl['PRIOR MARKET SALE PRICE'].replace(to_replace=0, value=neworl['PRIOR MARKET SALE PRICE'].mean(),inplace=True)
neworl['PRIOR LENGTH OF RESIDENCE'].replace(to_replace=0, value=neworl['PRIOR LENGTH OF RESIDENCE'].mean(),inplace=True)
neworl['LAST MARKET SALE PRICE'].replace(to_replace=0, value=neworl['LAST MARKET SALE PRICE'].mean(),inplace=True)
neworl['EQUITY ($)'].replace(to_replace=0, value=neworl['EQUITY ($)'].mean(),inplace=True)

In [155]:
baton['LENGTH OF RESIDENCE'].replace(to_replace=0, value=baton['LENGTH OF RESIDENCE'].mean(),inplace=True)
baton['PRIOR MARKET SALE PRICE'].replace(to_replace=0, value=baton['PRIOR MARKET SALE PRICE'].mean(),inplace=True)
baton['PRIOR LENGTH OF RESIDENCE'].replace(to_replace=0, value=baton['PRIOR LENGTH OF RESIDENCE'].mean(),inplace=True)
baton['LAST MARKET SALE PRICE'].replace(to_replace=0, value=baton['LAST MARKET SALE PRICE'].mean(),inplace=True)
baton['LAND VALUE'].replace(to_replace=0, value=baton['LAND VALUE'].mean(),inplace=True)

In [156]:
slidell['LENGTH OF RESIDENCE'].replace(to_replace=0, value=slidell['LENGTH OF RESIDENCE'].mean(),inplace=True)
slidell['PRIOR MARKET SALE PRICE'].replace(to_replace=0, value=slidell['PRIOR MARKET SALE PRICE'].mean(),inplace=True)
slidell['PRIOR LENGTH OF RESIDENCE'].replace(to_replace=0, value=slidell['PRIOR LENGTH OF RESIDENCE'].mean(),inplace=True)
slidell['LAST MARKET SALE PRICE'].replace(to_replace=0, value=slidell['LAST MARKET SALE PRICE'].mean(),inplace=True)
slidell['EQUITY ($)'].replace(to_replace=0, value=slidell['EQUITY ($)'].mean(),inplace=True)

In [157]:
jeff['LENGTH OF RESIDENCE'].replace(to_replace=0, value=jeff['LENGTH OF RESIDENCE'].mean(),inplace=True)
jeff['PRIOR MARKET SALE PRICE'].replace(to_replace=0, value=jeff['PRIOR MARKET SALE PRICE'].mean(),inplace=True)
jeff['PRIOR LENGTH OF RESIDENCE'].replace(to_replace=0, value=jeff['PRIOR LENGTH OF RESIDENCE'].mean(),inplace=True)
jeff['LAST MARKET SALE PRICE'].replace(to_replace=0, value=jeff['LAST MARKET SALE PRICE'].mean(),inplace=True)
jeff['EQUITY ($)'].replace(to_replace=0, value=jeff['EQUITY ($)'].mean(),inplace=True)
jeff['TOTAL ASSESSED VALUE'].replace(to_replace=0, value=jeff['TOTAL ASSESSED VALUE'].mean(),inplace=True)
jeff['LAND VALUE'].replace(to_replace=0, value=jeff['LAND VALUE'].mean(),inplace=True)

I set 'PROPERTY ADDRESS' as a index of dataframes.

In [158]:
jeff.set_index('PROPERTY ADDRESS',inplace=True)
slidell.set_index('PROPERTY ADDRESS',inplace=True)
neworl.set_index('PROPERTY ADDRESS',inplace=True)
baton.set_index('PROPERTY ADDRESS',inplace=True)

Now I have clear data and it is time to apply models on this data.

First model I want to try is "Gaussian Mixture Model", this algorithm will give me probabilities ang labels simultaneously.

In [159]:
jeff.corr()

PROPERTY TAX AMOUNT  PRIOR LENGTH OF RESIDENCE  \
PROPERTY TAX AMOUNT                   1.000000                  -0.100111   
PRIOR LENGTH OF RESIDENCE            -0.100111                   1.000000   
LAST MARKET SALE PRICE                0.455975                   0.051314   
PRIOR MARKET SALE PRICE               0.474335                  -0.299404   
LENGTH OF RESIDENCE                  -0.067734                  -0.055604   
LOT AREA                              0.004219                   0.027123   
EQUITY ($)                            0.430644                   0.059541   
IMPROVED %                            0.117202                  -0.194477   
LAND VALUE                            0.646580                   0.011488   
TAX REDUCTION                         0.695139                  -0.123419   
IMPROVED VALUE                        0.958709                  -0.130113   
TOTAL ASSESSED VALUE                  0.994548                  -0.106406   
LOT ACREAGE                           0.003043                   0.028484   

                           LAST MARKET SALE PRICE  PRIOR MARKET SALE PRICE  \
PROPERTY TAX AMOUNT                      0.455975                 0.474335   
PRIOR LENGTH OF RESIDENCE                0.051314                -0.299404   
LAST MARKET SALE PRICE                   1.000000                 0.464245   
PRIOR MARKET SALE PRICE                  0.464245                 1.000000   
LENGTH OF RESIDENCE                     -0.102140                -0.005376   
LOT AREA                                 0.019659                -0.033081   
EQUITY ($)                               0.940748                 0.441459   
IMPROVED %                              -0.154912                 0.083611   
LAND VALUE                               0.686020                 0.433932   
TAX REDUCTION                           -0.188188                 0.062744   
IMPROVED VALUE                           0.303267                 0.422175   
TOTAL ASSESSED VALUE                     0.453224                 0.480913   
LOT ACREAGE                              0.018880                -0.032312   

                           LENGTH OF RESIDENCE  LOT AREA  EQUITY ($)  \
PROPERTY TAX AMOUNT                  -0.067734  0.004219    0.430644   
PRIOR LENGTH OF RESIDENCE            -0.055604  0.027123    0.059541   
LAST MARKET SALE PRICE               -0.102140  0.019659    0.940748   
PRIOR MARKET SALE PRICE              -0.005376 -0.033081    0.441459   
LENGTH OF RESIDENCE                   1.000000  0.032001   -0.056832   
LOT AREA                              0.032001  1.000000    0.045789   
EQUITY ($)                           -0.056832  0.045789    1.000000   
IMPROVED %                           -0.057321 -0.080398   -0.165419   
LAND VALUE                           -0.013825  0.049345    0.668875   
TAX REDUCTION                        -0.021157  0.031425   -0.216800   
IMPROVED VALUE                       -0.080457 -0.011179    0.279113   
TOTAL ASSESSED VALUE                 -0.071823  0.004780    0.427920   
LOT ACREAGE                           0.030318  0.998033    0.045049   

                           IMPROVED %  LAND VALUE  TAX REDUCTION  \
PROPERTY TAX AMOUNT          0.117202    0.646580       0.695139   
PRIOR LENGTH OF RESIDENCE   -0.194477    0.011488      -0.123419   
LAST MARKET SALE PRICE      -0.154912    0.686020      -0.188188   
PRIOR MARKET SALE PRICE      0.083611    0.433932       0.062744   
LENGTH OF RESIDENCE         -0.057321   -0.013825      -0.021157   
LOT AREA                    -0.080398    0.049345       0.031425   
EQUITY ($)                  -0.165419    0.668875      -0.216800   
IMPROVED %                   1.000000   -0.453309       0.232260   
LAND VALUE                  -0.453309    1.000000       0.224997   
TAX REDUCTION                0.232260    0.224997       1.000000   
IMPROVED VALUE               0.301397    0.424496       0.756758   
TOTAL ASSESSED VALUE         0

In [160]:
neworl.corr()

PROPERTY TAX AMOUNT  PRIOR LENGTH OF RESIDENCE  \
PROPERTY TAX AMOUNT                   1.000000                  -0.143456   
PRIOR LENGTH OF RESIDENCE            -0.143456                   1.000000   
LAST MARKET SALE PRICE                0.782139                  -0.141080   
PRIOR MARKET SALE PRICE               0.781238                  -0.334079   
LENGTH OF RESIDENCE                   0.005820                  -0.048564   
EQUITY ($)                            0.867196                  -0.136315   

                           LAST MARKET SALE PRICE  PRIOR MARKET SALE PRICE  \
PROPERTY TAX AMOUNT                      0.782139                 0.781238   
PRIOR LENGTH OF RESIDENCE               -0.141080                -0.334079   
LAST MARKET SALE PRICE                   1.000000                 0.620927   
PRIOR MARKET SALE PRICE                  0.620927                 1.000000   
LENGTH OF RESIDENCE                      0.014571                -0.007575   
EQUITY ($)                               0.858062                 0.722889   

                           LENGTH OF RESIDENCE  EQUITY ($)  
PROPERTY TAX AMOUNT                   0.005820    0.867196  
PRIOR LENGTH OF RESIDENCE            -0.048564   -0.136315  
LAST MARKET SALE PRICE                0.014571    0.858062  
PRIOR MARKET SALE PRICE              -0.007575    0.722889  
LENGTH OF RESIDENCE                   1.000000    0.026500  
EQUITY ($)                            0.026500    1.000000

In [161]:
slidell.corr()

PROPERTY TAX AMOUNT  PRIOR LENGTH OF RESIDENCE  \
PROPERTY TAX AMOUNT                   1.000000                  -0.005639   
PRIOR LENGTH OF RESIDENCE            -0.005639                   1.000000   
LAST MARKET SALE PRICE                0.383599                   0.124906   
PRIOR MARKET SALE PRICE               0.165124                  -0.119520   
LENGTH OF RESIDENCE                  -0.001072                  -0.001256   
EQUITY ($)                            0.721383                  -0.043430   

                           LAST MARKET SALE PRICE  PRIOR MARKET SALE PRICE  \
PROPERTY TAX AMOUNT                      0.383599                 0.165124   
PRIOR LENGTH OF RESIDENCE                0.124906                -0.119520   
LAST MARKET SALE PRICE                   1.000000                 0.046536   
PRIOR MARKET SALE PRICE                  0.046536                 1.000000   
LENGTH OF RESIDENCE                     -0.049324                -0.088951   
EQUITY ($)                               0.627706                 0.090443   

                           LENGTH OF RESIDENCE  EQUITY ($)  
PROPERTY TAX AMOUNT                  -0.001072    0.721383  
PRIOR LENGTH OF RESIDENCE            -0.001256   -0.043430  
LAST MARKET SALE PRICE               -0.049324    0.627706  
PRIOR MARKET SALE PRICE              -0.088951    0.090443  
LENGTH OF RESIDENCE                   1.000000    0.001670  
EQUITY ($)                            0.001670    1.000000

In [162]:
baton.corr()

PROPERTY TAX AMOUNT  PRIOR LENGTH OF RESIDENCE  \
PROPERTY TAX AMOUNT                   1.000000                  -0.064693   
PRIOR LENGTH OF RESIDENCE            -0.064693                   1.000000   
LAST MARKET SALE PRICE                0.978562                  -0.049991   
PRIOR MARKET SALE PRICE               0.981299                  -0.045715   
LENGTH OF RESIDENCE                   0.047192                   0.051191   
LAND VALUE                            0.986294                  -0.053480   
LOT AREA                              0.005223                  -0.035921   
LOT ACREAGE                           0.005223                  -0.035921   

                           LAST MARKET SALE PRICE  PRIOR MARKET SALE PRICE  \
PROPERTY TAX AMOUNT                      0.978562                 0.981299   
PRIOR LENGTH OF RESIDENCE               -0.049991                -0.045715   
LAST MARKET SALE PRICE                   1.000000                 0.969422   
PRIOR MARKET SALE PRICE                  0.969422                 1.000000   
LENGTH OF RESIDENCE                      0.038080                 0.048906   
LAND VALUE                               0.966807                 0.975720   
LOT AREA                                 0.005039                 0.022925   
LOT ACREAGE                              0.005039                 0.022925   

                           LENGTH OF RESIDENCE  LAND VALUE  LOT AREA  \
PROPERTY TAX AMOUNT                   0.047192    0.986294  0.005223   
PRIOR LENGTH OF RESIDENCE             0.051191   -0.053480 -0.035921   
LAST MARKET SALE PRICE                0.038080    0.966807  0.005039   
PRIOR MARKET SALE PRICE               0.048906    0.975720  0.022925   
LENGTH OF RESIDENCE                   1.000000    0.042140 -0.005672   
LAND VALUE                            0.042140    1.000000  0.019836   
LOT AREA                             -0.005672    0.019836  1.000000   
LOT ACREAGE                          -0.005672    0.019836  1.000000   

                           LOT ACREAGE  
PROPERTY TAX AMOUNT           0.005223  
PRIOR LENGTH OF RESIDENCE    -0.035921  
LAST MARKET SALE PRICE        0.005039  
PRIOR MARKET SALE PRICE       0.022925  
LENGTH OF RESIDENCE          -0.005672  
LAND VALUE                    0.019836  
LOT AREA                      1.000000  
LOT ACREAGE                   1.000000

We see that 'LOT ACREAGE' and 'LOT AREA' highly correlated. Let's delete 'LOT ACREAGE'.

In [163]:
del baton['LOT ACREAGE'],jeff['LOT ACREAGE']

Now I use StandardScaler to standardise data.

In [164]:
from sklearn.preprocessing import StandardScaler

In [165]:
scaler = StandardScaler() 
scaler.fit(jeff)
jeff_sc= scaler.transform(jeff)

Now let's apply PCA transformation.

In [166]:
from sklearn.decomposition import PCA

In [167]:
model = PCA().fit(jeff_sc)

In [168]:
np.set_printoptions(suppress=True) 
model.explained_variance_ratio_

array([0.39243199, 0.19683718, 0.1058061 , 0.09067666, 0.07971006,
       0.068895  , 0.0398027 , 0.01390878, 0.00658132, 0.00473811,
       0.00061211, 0.        ])

In [169]:
model.explained_variance_

array([4.71899463, 2.36696705, 1.27231841, 1.09038685, 0.95851346,
       0.82846232, 0.47862743, 0.16725314, 0.07914039, 0.05697575,
       0.00736056, 0.        ])

In [170]:
model.explained_variance_ratio_.cumsum()[4]

0.86546198817458

In [171]:
pca_jeff = PCA(n_components=4).fit_transform(jeff_sc)

I also try hierarchical clustering, k-means clustering for actual data,scaled data and PCA transformed data, but thay give few "1" labels.

In [172]:
from sklearn.mixture import GaussianMixture
gmm = GaussianMixture(n_components=2, covariance_type = 'full',random_state=1)
gmmjf=gmm.fit(pca_jeff) 
gmm_jeff = gmmjf.predict(pca_jeff)
probgmmjf=gmmjf.predict_proba(pca_jeff)

In [173]:
scaler.fit(neworl)
new_sc= scaler.transform(neworl)

In [174]:
model1 = PCA().fit(new_sc)

In [175]:
model1.explained_variance_ratio_

array([0.5633839 , 0.172475  , 0.15994431, 0.0603623 , 0.02560832,
       0.01822617])

In [176]:
model1.explained_variance_

array([3.3875263 , 1.03706119, 0.9617164 , 0.36294766, 0.15397825,
       0.10959072])

In [177]:
model1.explained_variance_ratio_.cumsum()[2]

0.8958032057098558

In [178]:
pca_new = PCA(n_components=2).fit_transform(new_sc)


In [179]:
gmmnew=gmm.fit(pca_new)
gmm_new = gmmnew.predict(pca_new)
probgmmnew=gmmnew.predict_proba(pca_new)

In [180]:
scaler.fit(baton)
baton_sc= scaler.transform(baton)

In [181]:
model2 = PCA().fit(baton_sc)

In [182]:
model2.explained_variance_ratio_

array([0.56225437, 0.15213473, 0.14192442, 0.13363516, 0.00496074,
       0.00353236, 0.00155822])

In [183]:
model2.explained_variance_

array([3.93996759, 1.06607603, 0.99452779, 0.93644127, 0.03476213,
       0.02475284, 0.01091916])

In [184]:
model1.explained_variance_ratio_.cumsum()[2]

0.8958032057098558

In [185]:
pca_baton = PCA(n_components=2).fit_transform(baton_sc)

In [186]:
gmmb=gmm.fit(baton_sc) 
gmm_baton = gmmb.predict(baton_sc)
probgmmb= gmmb.predict_proba(baton_sc)

In [187]:
scaler.fit(slidell)
slidell_sc= scaler.transform(slidell)

In [188]:
model3 = PCA().fit(slidell_sc)

In [189]:
model3.explained_variance_

array([2.20943441, 1.16527016, 1.02767566, 0.84895823, 0.58919399,
       0.20358519])

In [190]:
model3.explained_variance_ratio_.cumsum()[3]

0.8688345875427259

In [191]:
pca_sl = PCA(n_components=3).fit_transform(slidell_sc)

In [192]:
gmmsl=gmm.fit(slidell_sc) 
gmm_sl = gmmsl.predict(slidell_sc)
probgmmsl=gmmsl.predict_proba(slidell_sc)

For "slidell" and "baton" most "1" label gives scaled data and for "jeff" and "neworl" pca-transformed data.

For logistic regression let's attach dummy variables.

In [193]:
j.set_index(jeff.index,inplace=True)
s.set_index(slidell.index,inplace=True)
n.set_index(neworl.index,inplace=True)
b.set_index(baton.index,inplace=True)
j1.set_index(jeff.index,inplace=True)
s1.set_index(slidell.index,inplace=True)
n1.set_index(neworl.index,inplace=True)
b1.set_index(baton.index,inplace=True)

In [194]:
jeff=pd.concat([jeff,j1,j],axis=1)
neworl=pd.concat([neworl,n1,n],axis=1)
slidell=pd.concat([slidell,s1,s],axis=1)
baton=pd.concat([baton,b1,b],axis=1)

In [195]:
del baton['OTHER1'],neworl["OTHER1"],slidell["OTHER1"],jeff['OTHER1']
del baton['Other'],neworl["Other"],slidell["Other"],jeff['Other']

I consider jeff as a test dataset, jeff dataset labels will be GMM's labels.

In [196]:
from sklearn.linear_model import LogisticRegression

In [197]:
XB=jeff[baton.columns]

In [198]:
log = LogisticRegression()
lrb=log.fit(XB, gmm_jeff)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [199]:
lr_baton = lrb.predict(baton)
problrb=lrb.predict_proba(baton)

In [200]:
XS=jeff[slidell.columns]
lrs = log.fit(XS, gmm_jeff)
lr_slidell = lrs.predict(slidell)
problrsl=lrs.predict_proba(slidell)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [201]:
XN=jeff[neworl.columns]
lrn = log.fit(XN, gmm_jeff)
lr_new = lrn.predict(neworl)
problrnew= lrn.predict_proba(neworl)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [202]:
lrj = log.fit(jeff, gmm_jeff)
lr_jeff = lrj.predict(jeff)
problrjeff= lrj.predict_proba(jeff)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Now let's calculate how match gmm and lr labels matches.

In [203]:
from sklearn.metrics import confusion_matrix

In [204]:
confusion_matrix(lr_jeff,gmm_jeff)

array([[444,  16],
       [ 11,  10]])

In [205]:
confusion_matrix(lr_baton,gmm_baton)

array([[ 53, 877],
       [  7,   4]])

In [206]:
confusion_matrix(lr_slidell,gmm_sl)

array([[102,  19],
       [  7,   9]])

In [207]:
confusion_matrix(lr_new,gmm_new)

array([[361,  55],
       [ 17,  36]])

In [208]:
from sklearn.metrics import accuracy_score 
accuracy_score(lr_baton,gmm_baton)

0.06057385759829968

Accuracy score is low because "1" and "0" labels was opposite.

In [209]:
gmm_baton

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [210]:
gmm_baton=np.where(gmm_baton==1, 0, 1)

In [211]:
gmm_baton

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [212]:
probgmmb

array([[0.00000002, 0.99999998],
       [0.00000001, 0.99999999],
       [0.        , 1.        ],
       ...,
       [0.00000002, 0.99999998],
       [0.00000002, 0.99999998],
       [0.00000003, 0.99999997]])

In [213]:
gmm0=probgmmb[:,1]

In [214]:
gmm1=probgmmb[:,0]

In [215]:
probgmmb=np.array([gmm0,gmm1]).T

In [216]:
accuracy_score(lr_baton,gmm_baton)

0.9394261424017003

In [217]:
accuracy_score(lr_slidell,gmm_sl)

0.8102189781021898

In [218]:
accuracy_score(lr_new,gmm_new)

0.8464818763326226

In [219]:
accuracy_score(lr_jeff,gmm_jeff)

0.9438669438669439

We can see that gmm and lr labels not match perfectly. That's why I decide to take the mean of gmm and lr probabilities.

In [220]:
baton['LRLABEL']=lr_baton
baton['GMMLABEL']=gmm_baton

In [221]:
slidell['LRLABEL']=lr_slidell
slidell['GMMLABEL']=gmm_sl

In [222]:
neworl['LRLABEL']=lr_new
neworl["GMMLABEL"]=gmm_new

In [223]:
jeff["GMMLABEL"]=gmm_jeff
jeff["LRLABEL"]=lr_jeff

In [224]:
probsl=(problrsl+probgmmsl)/2

In [225]:
probnew=(problrnew+probgmmnew)/2

In [226]:
probbaton=(problrb+probgmmb)/2

In [227]:
probjeff=(problrjeff+probgmmjf)/2

Where probability greather than 0.5 let's give that datapoint "1" label

In [228]:
neworl['LABEL']=np.where(probnew[:,1]>=0.5, 1, 0)

In [229]:
slidell['LABEL']=np.where(probsl[:,1]>=0.5, 1, 0)

In [230]:
baton['LABEL']=np.where(probbaton[:,1]>=0.5, 1, 0)

In [231]:
jeff['LABEL']=np.where(probjeff[:,1]>=0.5, 1, 0)

Let's create new columns for probability and label.

In [232]:
slidell["PROB"]=probsl[:,1]
neworl["PROB"]=probnew[:,1]
jeff["PROB"]=probjeff[:,1]
baton["PROB"]=probbaton[:,1]

In [233]:
baton0=baton[baton['LABEL']==0]
baton1=baton[baton['LABEL']==1]

In [234]:
jeff0=jeff[jeff['LABEL']==0]
jeff1=jeff[jeff['LABEL']==1]

In [235]:
neworl0=neworl[neworl['LABEL']==0]
neworl1=neworl[neworl['LABEL']==1]

In [236]:
slidell0=slidell[slidell['LABEL']==0]
slidell1=slidell[slidell['LABEL']==1]

To know which label means that asset will be sold, let's do some research.

First of all let's explain variables.

In [237]:
jeff.columns

Index(['PROPERTY TAX AMOUNT', 'PRIOR LENGTH OF RESIDENCE',
       'LAST MARKET SALE PRICE', 'PRIOR MARKET SALE PRICE',
       'LENGTH OF RESIDENCE', 'LOT AREA', 'EQUITY ($)', 'IMPROVED %',
       'LAND VALUE', 'TAX REDUCTION', 'IMPROVED VALUE', 'TOTAL ASSESSED VALUE',
       'Deed (Reg)', 'Limited Warranty Deed', 'Quit Claim Deed',
       'Special Warranty Deed', 'Ave', 'Blvd', 'Cir', 'Ct', 'Dr', 'Ln', 'Pl',
       'Rd', 'St', 'GMMLABEL', 'LRLABEL', 'LABEL', 'PROB'],
      dtype='object')

 # 4. GOAL  METADATA
PRIOR MARKET SALE PRICE   - money,that prior owner paid to buy asset.\
LAST MARKET SALE PRICE    - money,that prior owner paid to buy asset.\
PROPERTY TAX AMOUNT       - tax value for asset.\
PRIOR LENGTH OF RESIDENCE - lengt that prior resident owned asset (by mouths)\
LENGTH OF RESIDENCE       - lengt that last resident owns asset (by mouths)\
IMPROVED VALUS            - spent money for improving asset.\
IMPROVED %                - percentage of asset that improved.\
TOTAL ASSESSED VALUE      - value assigned to a property to measure applicable taxes.\
LOT AREA                  - total horizontal area within the lines of the lot.\
EQUITY ($)                - market value of asset.\
TAX REDUCTION             - reduced percentage of asset tax during years.\
LAND VALUE                - measure of how much a plot of land is worth.\

A property deed is a written and signed legal instrument that is used to transfer ownership of real property from the old owner to the new owner. 

A street suffix is the word that follows the name of a street to further describe that street.

In [238]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [239]:
(baton1.describe()-baton0.describe()).iloc[:,:7]

PROPERTY TAX AMOUNT  PRIOR LENGTH OF RESIDENCE  LAST MARKET SALE PRICE  \
count             -827.000                   -827.000                -827.000   
mean              6303.296                    -29.691              925347.178   
std              22390.905                    -14.470             3034861.760   
min                241.520                      0.000               41000.000   
25%                559.527                    -41.750              157000.000   
50%               1412.080                      0.000              365000.000   
75%               4246.780                    -17.003              448020.000   
max             150753.020                    -73.000            19386600.000   

       PRIOR MARKET SALE PRICE  LENGTH OF RESIDENCE  LAND VALUE      LOT AREA  
count                 -827.000             -827.000    -827.000      -827.000  
mean                587011.964                0.318    9587.557   7305064.557  
std                2270492.280               -1.188   34152.778  53993187.795  
min                  17900.000                0.000     390.000         0.000  
25%                  28321.676                1.000    1170.000     10532.250  
50%                      0.000                1.000    2300.000     85930.500  
75%                 335803.324                0.000    6627.500    225650.750  
max               15355000.000              -63.000  240000.000 407802911.000

In [240]:
(jeff1.describe()-jeff0.describe()).iloc[:,:12]

PROPERTY TAX AMOUNT  PRIOR LENGTH OF RESIDENCE  LAST MARKET SALE PRICE  \
count             -441.000                   -441.000                -441.000   
mean              4412.273                     -1.622              364633.144   
std               5502.780                     15.005              255472.987   
min                756.370                      0.000               19999.000   
25%               1528.497                    -46.500              178000.000   
50%               3083.740                     17.555              355000.000   
75%               5901.382                     14.500              433098.750   
max              25000.100                    -48.000              890000.000   

       PRIOR MARKET SALE PRICE  LENGTH OF RESIDENCE      LOT AREA  EQUITY ($)  \
count                 -441.000             -441.000      -441.000    -441.000   
mean                174315.714                0.079 199747116.124  380220.477   
std                 186445.687                0.317 404961975.826  250799.863   
min                  57320.000                0.000         0.000   22000.000   
25%                  18843.798               -1.000      3705.000  182650.000   
50%                 144156.202                1.500      2614.500  363400.000   
75%                 218500.000                0.000      5889.000  562650.000   
max                 570000.000               -1.000 883476999.000  579300.000   

       IMPROVED %  LAND VALUE  TAX REDUCTION  IMPROVED VALUE  \
count    -441.000    -441.000       -441.000        -441.000   
mean      -10.460   11892.775          7.952       26536.390   
std         9.745    8112.915         29.284       45185.994   
min         0.000    1750.000          1.000           0.000   
25%       -24.250    4232.500         -2.000        1052.500   
50%        -7.000   10895.000         -1.000       12700.000   
75%         3.500   17265.000          3.000       38287.500   
max        -1.000   20530.000        124.000      195140.000   

       TOTAL ASSESSED VALUE  
count              -441.000  
mean              38429.166  
std               48710.387  
min                5490.000  
25%               13342.500  
50%               25720.000  
75%               51870.000  
max              220460.000

In [241]:
(neworl1.describe()-neworl0.describe()).iloc[:,:6]

PROPERTY TAX AMOUNT  PRIOR LENGTH OF RESIDENCE  LAST MARKET SALE PRICE  \
count             -303.000                   -303.000                -303.000   
mean              5589.513                    -74.248              437732.497   
std               4207.944                    -46.117              320474.712   
min               1869.170                      1.000               51300.000   
25%               3889.915                    -66.750              278750.000   
50%               4327.045                    -42.000              381000.000   
75%               6016.020                   -125.750              453500.000   
max              29380.890                   -425.000             1727945.000   

       PRIOR MARKET SALE PRICE  LENGTH OF RESIDENCE  EQUITY ($)  
count                 -303.000             -303.000    -303.000  
mean                280491.947                0.334  457783.413  
std                 279971.972               -0.045  289999.579  
min                  35500.000                1.000  153787.000  
25%                 107371.676                1.000  314214.750  
50%                 220310.000                0.000  377909.000  
75%                 323529.824                0.000  471362.500  
max                2100000.000                0.000 1852711.000

In [242]:
(slidell1.describe()-slidell0.describe()).iloc[:,:6]

PROPERTY TAX AMOUNT  PRIOR LENGTH OF RESIDENCE  LAST MARKET SALE PRICE  \
count              -85.000                    -85.000                 -85.000   
mean              2082.840                      5.848              215958.462   
std               2490.483                      3.445              362979.443   
min                 64.570                      3.000              -35800.000   
25%                422.082                     27.500               -2500.000   
50%               1276.970                      0.000              156250.000   
75%               3313.008                     -4.000              325500.000   
max              10565.690                     -2.000             1833500.000   

       PRIOR MARKET SALE PRICE  LENGTH OF RESIDENCE  EQUITY ($)  
count                  -85.000              -85.000     -85.000  
mean                   157.415               -0.011  165519.785  
std                -340151.294               -0.758  113544.150  
min                  22000.000                1.000   38100.000  
25%                  46196.676                1.000   84650.000  
50%                   1182.543                1.000  129650.000  
75%                  22620.781               -0.250  223250.000  
max               -4086500.000              -14.000  430900.000

We can see above that class "1" assets are more expensive and bigger than label "0" assets, this means that thay will get more money if thay sell equity. Taxes are higher (to control urbanisation governments play with taxes, thay reduce tax in special area to promote living in that area). We also see that people ownes label "1" equities more long than label "0" equites. So we can conclude that , equities which have label "1" will sell their equity.

In [243]:
batonfin=baton.iloc[:,-2:]
slidellfin=slidell.iloc[:,-2:]
jefffin=jeff.iloc[:,-2:]
neworlfin=neworl.iloc[:,-2:]

In [244]:
neworlfin

LABEL  PROB
PROPERTY ADDRESS             
481                   0 0.100
482                   1 0.836
483                   0 0.042
484                   0 0.065
485                   0 0.048
...                 ...   ...
945                   0 0.004
946                   0 0.126
947                   0 0.189
948                   0 0.002
949                   0 0.011

[469 rows x 2 columns]

In [245]:
fin=pd.concat([batonfin,slidellfin,jefffin,neworlfin])

In [246]:
fin.sort_values(by=['PROB'],ascending=False,inplace=True)

In [247]:
fin

LABEL  PROB
PROPERTY ADDRESS             
80                    1 1.000
889                   1 1.000
841                   1 1.000
974                   1 1.000
527                   1 1.000
...                 ...   ...
1487                  0 0.000
1542                  0 0.000
1762                  0 0.000
1383                  0 0.000
1046                  0 0.000

[2028 rows x 2 columns]

In [248]:
(fin["LABEL"]==1).sum()

186

So if we choose probability treshold 0.5, 182 owner will sell their equities.
If client want other threshold, he or she can just input treshold below.

In [249]:
tr=input("Treshold ")

Treshold 0.3


In [250]:
fin['LABEL']=np.where(fin['PROB']>=float(tr), 1, 0)

In [251]:
number_of_selling_equities=(fin["LABEL"]==1).sum()

# 2. GOAL

In [252]:
number_of_selling_equities

241

In [253]:
last=fin[fin["LABEL"]==1]

In [254]:
selling_addresses=last.index.values

In [255]:
selling_addresses

array([  80,  889,  841,  974,  527,  361,  313,  584,  271, 1082,  515,
        894,  535,  464,  690,  975,  284,  494,  583,  751, 1065,  877,
        865, 1740, 1083, 1951,  705,  640,  651, 1881,  632,  508,  907,
        497,  896,  429,   99,  482, 1066,  695,  998, 1132,  653,  855,
        294,  827,  626,  689, 1124,  818, 1053, 1007,  828, 1331,  615,
        832,   38,  561,  939,  796, 2024, 1039, 1709,  375, 1472,  914,
        641,  688,  578,  846,  930,  926,  606,  672, 1048, 1035,  863,
        614,  803,  692,  546,  486,  531, 1319,  781,  301,  853,  745,
       1891,  739, 1544,  852, 1049, 1729,  912,  495,  967,  937,  492,
       1589, 1423,  838,  791, 1700,  549, 1146,  605,  559, 1532,  681,
       1892, 1017,  570, 1553,  676, 1572, 1037, 1728, 1868, 1051,  942,
        957,  746, 1145, 1055, 1095, 1694,  825,  685, 1060, 1113,  547,
       1467,  976,  977, 1001, 1363,  859, 1131, 1485, 1119,  848,  587,
        927, 1504, 1344,  200, 1593, 1019,  337,  2

In [256]:
del last["LABEL"]

# 1. GOAL

In [257]:
last

PROB
PROPERTY ADDRESS      
80               1.000
889              1.000
841              1.000
974              1.000
527              1.000
...                ...
659              0.304
228              0.303
935              0.303
1050             0.302
608              0.301

[241 rows x 1 columns]

# 3. GOAL 
I think this data is not worth of buying, because there are many missing values on it and unusfull columns. If there be other variables, for example how many people living in that house, their budget, distance from city center, it will be more usefull.
 